@echo off
start chrome "https://mail.google.com"
start chrome "https://huggingface.co"
start chrome "https://openrouter.ai"
start chrome "https://cloud.cerebras.ai"
start chrome "https://cloud.sambanova.ai/apis"
start chrome "https://groq.com"
start chrome "https://platform.claude.com/settings/workspaces/default/keys"
start chrome "https://platform.kimi.ai/console/api-keys"
start chrome "https://platform.deepseek.com/api_keys"
start chrome "https://www.mulerouter.ai/app/api-keys"
start chrome "https://console.cloud.google.com/home"
start chrome "https://aistudio.google.com/api-keys"
start chrome "https://build.nvidia.com/settings/api-keys"
start chrome "https://tinker.thinkingmachines.ai/keys"
start chrome "https://www.kaggle.com/"
start chrome "https://console.paperspace.com/login"
start chrome "https://ollama.com/settings/keys"
exit
